export const integrations = [
  {
    name: "LinkedIn",
    category: "Professional Network",
    logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg",
    badge: "Exclusive",
    color: "from-blue-600 to-blue-700",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    borderColor: "border-blue-200 dark:border-blue-700",
    description: "Direct Recruiter API integration",
    features: [
      "Real-time candidate search",
      "Advanced filtering",
      "Direct messaging",
    ],
  },
  {
    name: "Indeed",
    category: "Job Board",
    logo: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Indeed_logo.svg",
    badge: "Direct Feed",
    color: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    borderColor: "border-blue-200 dark:border-blue-700",
    description: "Global job board integration",
    features: [
      "Resume database access",
      "Job posting sync",
      "Application tracking",
    ],
  },
  {
    name: "Monster",
    category: "Job Board",
    logo: "https://seekvectorlogo.com/wp-content/uploads/2019/11/monster-com-vector-logo-small.png",
    badge: "Real-time",
    color: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-50 dark:bg-purple-900/20",
    borderColor: "border-purple-200 dark:border-purple-700",
    description: "Career platform integration",
    features: ["Candidate profiles", "Skills matching", "Industry insights"],
  },
  {
    name: "CareerBuilder",
    category: "Job Board",
    logo: "https://cdn.brandfetch.io/idRrcMU04X/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1748624187091",
    badge: "Premium",
    color: "from-orange-500 to-orange-600",
    bgColor: "bg-orange-50 dark:bg-orange-900/20",
    borderColor: "border-orange-200 dark:border-orange-700",
    description: "Comprehensive talent solutions",
    features: ["Resume search", "Talent network", "Hiring insights"],
  },
  {
    name: "Greenhouse",
    category: "ATS",
    logo: "https://cdn.brandfetch.io/idr54tWwj4/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1696624241411",
    badge: "ATS Sync",
    color: "from-green-500 to-green-600",
    bgColor: "bg-green-50 dark:bg-green-900/20",
    borderColor: "border-green-200 dark:border-green-700",
    description: "Applicant tracking system",
    features: [
      "Pipeline management",
      "Interview scheduling",
      "Candidate scoring",
    ],
  },
  {
    name: "Lever",
    category: "ATS",
    logo: "https://www.lever.co/wp-content/uploads/2022/09/Lever_Employ_Logo_Horizontal_Turquoise_Black.png",
    badge: "Bi-directional",
    color: "from-indigo-500 to-indigo-600",
    bgColor: "bg-indigo-50 dark:bg-indigo-900/20",
    borderColor: "border-indigo-200 dark:border-indigo-700",
    description: "Modern recruiting platform",
    features: ["CRM integration", "Analytics dashboard", "Team collaboration"],
  },
  {
    name: "Workday",
    category: "ATS",
    logo: "https://cdn.brandfetch.io/id0V-YF4nE/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1739332027230",
    badge: "Enterprise",
    color: "from-blue-600 to-blue-700",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    borderColor: "border-blue-200 dark:border-blue-700",
    description: "Enterprise HR platform",
    features: [
      "Employee data sync",
      "Workflow automation",
      "Compliance tracking",
    ],
  },
  {
    name: "Bullhorn",
    category: "ATS",
    logo: "https://cdn.brandfetch.io/idA9IQyEKD/theme/dark/logo.svg?c=1bxid64Mup7aczewSAYMX&t=1747754473033",
    badge: "HR Sync",
    color: "from-green-600 to-green-700",
    bgColor: "bg-green-50 dark:bg-green-900/20",
    borderColor: "border-green-200 dark:border-green-700",
    description: "Human resources software",
    features: [
      "Employee records",
      "Performance tracking",
      "Benefits management",
    ],
  },
];
